version: "3.9"
services:
  # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
  mario-app:
    container_name: mario-app
    build: .
    restart: unless-stopped
    env_file: ./.env
    network_mode: host
    ports:
      - $PORT:$PORT
  # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - mysql:/var/lib/mysql
  # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
volumes:
  mysql:
